### PR TITLE
Issue-88: add to homescreen prompt

### PR DESCRIPTION
**Pull request by hizo**
https://github.com/nearform/react-pwa/issues/88

Adds automatic add to homescreen prompt in supported browsers - currently only Android Chrome and desktop Chrome.
On desktop, you need to enable experimental flag #enable-desktop-pwas. Full support for desktop PWAs coming in Chrome v72.

In unsupported browsers we show a fallback with instructions on how to add to homescreen manually. I made it so that it is shown only on mobile browsers, since desktop PWAs are not yet supported anywhere.

How to test:
- I used Android emulator from Android Studio (can showcase a demo upon request)
- enable the experimental flag in Chrome
- if you are testing on Android Chrome, one of the requirements for it to appear is to be interacting with the page for at least 30 seconds (more or less)
- if running locally, you need to expose your localhost:3000 on some temporary domain with https enabled, I suggest this tool https://ngrok.com/

### CODE REVIEW

**Comment by simoneb** [comment]
When trying this out locally I'm definitely prompted for installation, but I'm not sure this is implemented properly. I don't know much about PWAs, but as far as my understanding goes you shouldn't need to write much custom code for that to happen **on mobile**.

Here's what happens on an Android mobile device:

image

In other words, I get both the custom prompt and the native browser prompt. I have a feeling that on mobile, we don't need to write a single line of code to make the app installable.

On the other hand, on desktop I get only the custom install prompt. I'm not sure if the intention is to make this app installable both on mobile and desktop, but if that's the case, then we need to find a way to prevent the custom dialog from appearing on devices where the native one appears instead.

**Comment by hizo** [comment]
https://developers.google.com/web/fundamentals/app-install-banners/ you can read about the prompt here.

Nice catch overall, but:
The thing is, before Chrome 67, there used to be an automatic prompt (a bit different from the one you posted). That was removed in Chrome 68. Now you need to wait for `beforeinstallprompt` event and show a custom UI to the user. Furthermore, to keep the experience consistent, I am doing `e.preventDefault()` when the browser event fires, so that it doesnt show that automatic popup in Chrome < 68.

What you are experiencing on your device is described here https://developers.google.com/web/fundamentals/app-install-banners/#the_mini-info_bar . This mini bar displays even when `e.preventDefault()` is called when the browser event is triggered and it is considered an interim experience. 

So currently, there is no consitent way to do this. The only fix that comes to my mind is userAgent sniffing and check whether user is on a specific Android Chrome version... but the document from chrome doesn't specify on which browsers is the mini bar displayed. The mini bar also might get deleted in the future, they are not decided yet and it's not a final solution.

The mini info bar didnt show up in my tests in Android emulator.

What do you suggest I do for a fix?

**Comment by simoneb** [comment]
Here's how I would reason about it.

Do we need to be able to install the app on desktop? 
I don't see any benefit in that. PWAs are mostly for mobile, on desktop you don't have the constraints you have on mobile.
Hence, if we only need it for mobile, then we probably don't need to write a single line of code.

So my question is, why did we think we needed to do this?

**Comment by hizo** [comment]
@dberesford was asking why the popup is not shown on his iPad, so Safari iOS.

Also, the mini info bar, once dismissed, will not show up for about 3 months according to the google documentation.

Our solution with listening to the `beforeinstallprompt` event will fire every time you visit the page unless you already clicked install. Thats why I think it's better.

Otherwise, there is not much added value, since we can only display some prompt on unsupported devices with instructions on how to manually add it to home screen - the same way it is displayed now.

**Pull request merged**
