### PR TITLE
Replaced SASS and CSS with typestyle.

### PR DESCRIPTION
**Pull request by ShogunPanda**
I’ve completed the spike on integrating [typestyle](https://github.com/typestyle/typestyle). 
The benefit are the following:

1. You can write CSS in the JS (SSR supported), keeping all the components code in a single file.
2. You make sure the component uses declared classes and that there are no unused rules.
3. Via `require`, class reusing is really easy without the need to have a component use multiple classes.
4. All the flexibility of JS to generate CSS, including interpolation, spread/rest operators and so on.

### CODE REVIEW

**Comment by temsa** [comment]
@ShogunPanda you forgot to update the readme to remove references to SASS :)

**Comment by ShogunPanda** [comment]
@bmullan91 

I've evaluated several options (I don't recall the names right now but I looked at the most known).
Long story short, all of them but two ([glamor](https://github.com/threepointone/glamor) and typestyle) forced you to embed regular tags in a HOC approach and more over often you kept writing raw CSS in JS using templates.

glamor and typestyle instead let you write JS pure code (and with the plus of TS definitions in the latter) and then use the classes without using weird encapsulation.
At the end I chose typestyle because glamor seems to be dead.

Your point about simplicity is right, but since we want to focus on client side performances for the PWA, removing a network request (since no CSS must be fetched) should be a good hint.

**Comment by temsa** [comment]
@bmullan91 are you :ok_hand: to merge then ?

**Comment by bmullan91** [comment]
@ShogunPanda @temsa What if we link to a list of 'forks' that have used this but with adaptations?

Next.js for example has a list of `examples` https://github.com/zeit/next.js/tree/canary/examples

In our case it'd be a list in the README.md of forks. Others might include:

- typescript
- preact
- styled-components
- etc

**Comment by ShogunPanda** [comment]
Sounds completely fine to me!

**Comment by ShogunPanda** [comment]
I've updated this branch to also include tree shaking, therefore switching to ES6 modules.
Since CSS in JS is not universally accepted, with @dberesford we agreed on NOT TO merge this PR but keeping the branch.

**Pull request closed without merging**
